apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workloadupdateconfigs.workloadupdate.k8s.io
spec:
  group: workloadupdate.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maintainanceWindow:
                  type: object
                  properties:
                    start:
                      type: string
                    end:
                      type: string
  scope: Namespaced
  names:
    plural: workloadupdateconfigs
    singular: workloadupdateconfig
    kind: WorkloadUpdateConfig
    shortNames:
      - wuc
